name: "dotnet-format"

description: "Run dotnet format and optionally apply any fixes"

author: 
  - "jfversluis"
  - "xt0rted"
  - "victor-alcazar"
  
branding:
  icon: "file-text"
  color: "purple"

inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true

  action:
    description: "The primary action dotnet-format should perform (check for errors or apply fixes)"
    required: false
    default: "check"

  only-changed-files:
    description: "Only changed files in the current pull request should be formatted"
    required: false

  fail-fast:
    description: "The job should fail if there's a formatting error"
    required: false
    default: "true"

  include:
    description: "The files to include, delimited by space. Cannot be used with the `--workspace` option"
    required: false

  workspace:
    description: "The solution or project file to operate on"
    required: false

  exclude:
    description: "Option to ignore given files/folders"
    required: false

  logLevel:
    description: "Sets the logging verbosity of the dotnet format process. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]"
    required: false

outputs:
  has-changes:
    description: "A value indicating if any files were formatted"

runs:
  using: "node12"
  main: "dist/index.js"
